@echo off
setlocal EnableDelayedExpansion
cd /d "%~dp0.."

echo ====================================
echo Starting Home Automation Application
echo ====================================
echo.

echo 1. Checking for existing JAR...
if not exist "target\home-automation-0.0.1-SNAPSHOT.jar" (
    echo ! JAR not found! Building application first...
    call mvn package -DskipTests -q
    if !errorlevel! neq 0 (
        echo Failed to build application!
        pause
        exit /b 1
    )
)

echo    Application JAR found/created
echo.

echo 2. Resolving JWT_SECRET...
if defined JWT_SECRET (
    echo    JWT_SECRET already set in environment - using it.
) else if exist ".env" (
    echo    Loading JWT_SECRET from .env ...
    for /f "usebackq tokens=1,* delims==" %%a in (".env") do (
        if /i "%%a"=="JWT_SECRET" set "JWT_SECRET=%%b"
    )
)

if not defined JWT_SECRET (
    echo    No .env found - generating a random secret once and saving it...
    for /f %%s in ('powershell -NoProfile -Command "$c='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'; $r=[System.Security.Cryptography.RandomNumberGenerator]::Create(); $b=New-Object byte[] 48; $r.GetBytes($b); -join ($b | ForEach-Object { $c[$_ %% 62] })"') do set "JWT_SECRET=%%s"
    (
        echo # Local environment variables - DO NOT COMMIT (git-ignored^).
        echo # Generated by scripts\start-app-8081.bat. Keeps JWT_SECRET stable between runs.
        echo JWT_SECRET=!JWT_SECRET!
    ) > .env
    echo    Secret generated and saved to .env
)
echo    JWT_SECRET is set (length: ok).
echo.

echo 3. Stopping any existing instance on port 8081...
for /f "tokens=5" %%a in ('netstat -ano ^| findstr :8081') do (
    taskkill /PID %%a /F >nul 2>&1
    echo    Killed PID %%a
)

echo.
echo 4. Starting Spring Boot on port 8081 (profile: local)...
echo    This may take a few seconds...
echo.

java -jar target/home-automation-0.0.1-SNAPSHOT.jar --server.port=8081 --spring.profiles.active=local

echo.
echo Application stopped.
echo ====================================
endlocal
